### ISSUE TITLE
Log event naming convention (MITx DLL)

### ISSUE THREAD

**Issue by msegado** [Colin-Fredericks/edx-undocumented#1]
In case it's helpful, here's a suggestion I sent to MIT's Digital Learning Lab some time back (modified to remove project-specific details):

---

I've been working on a project which requires custom tracking-log events and found the following guidance on event names in the [edX developer guide](http://edx.readthedocs.io/projects/edx-developer-guide/en/latest/analytics.html):

> Event names are intended to be formatted as . separated strings and help processing of related events. The structure is intended to be namespace.object.action. The namespace is intended to be a . separated string that helps identify the source of events and prevent events with similar or identical objects and actions from being confused with one another. The object is intended to be a noun describing the object that was acted on. The action is intended to be a past tense verb describing what happened.
> 
> Examples:
>   * `edx.course.enrollment.activated`
>     * Namespace: `edx`
>     * Object: `course.enrollment`
>     * Action: `activated`

Per that advice, what do folks think of settling on "mitx.dll" as a namespace for DLL experimental/research events, followed by the name of the project/tool? For example, here are the events I'm logging in the latest version of my "supercool" project:
* `mitx.dll.supercool.loaded` - logged when the script is loaded
* `mitx.dll.supercool.error` - logged when the script catches an internal error
* `mitx.dll.supercool.cool_item.transformed` - logged after the script transforms the cool_item

To avoid naming collisions, we could maintain a shared spreadsheet of the different project names in use... that way nobody accidentally names their events mitx.dll.supercool.* for example. I'd be glad to coordinate the effort if people think it's a good idea!

---

Feel free to co-opt all or part of this for the wiki page on logging events.

**Comment by Colin-Fredericks** [comment]
Added to the logging page. Thanks!
